Inventory terraform_state - supports groups
ansible-collections/cloud.terraform pull request #121
Opened 2024-03-21 12:41 UTC by akira6592

##### SUMMARY

Supports `groups`.

```yaml
---
plugin: cloud.terraform.terraform_state
backend_type: s3
backend_config:
  bucket: {{ bucket_name }}
  key: ansible/terraform.tfstate
  region: {{ aws_region }}
keyed_groups:
  - key: instance_state
    prefix: state
  - prefix: tag
    key: tags
groups:    # here
  no_public_ip: public_ip == ""
```
##### ISSUE TYPE

- Bugfix Pull Request
- Feature Pull Request

##### COMPONENT NAME

- `terraform_state` inventory plugin

##### ADDITIONAL INFORMATION

```paste below

```

2024-03-22 20:13 UTC, hakbailey requested changes
@akira6592 Thank you for submitting this PR! It looks good to me except it needs a changelog fragment. Could you add that please?

2024-03-22 20:26 UTC, hakbailey approved these changes

2024-03-23 04:56 UTC, akira6592 commented
@hakbailey Thank you for reviewing and approval. I'm looking forward to release this inventory plugin.

2024-03-25 09:46 UTC, abikouo approved these changes

2024-03-27 08:25 UTC, merged

2024-03-27 11:53 UTC, akira6592 commented
Thank you for merging