Code refactoring, CI improvements, cruft removal
ansible-collections/cloud.terraform pull request #20
Opened 2022-12-13 06:18 UTC by sstanovnik

##### SUMMARY

Huge refactoring including CI pipelines and linters.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

##### ADDITIONAL INFORMATION

See the commits which include all necessary descriptions.

2022-12-13 10:40 UTC, abikouo commented on plugins/module_utils/models.py
> +from __future__ import absolute_import, division, print_function
this can be removed as we are going to support python3+ only for this collection

2022-12-13 11:37 UTC, abikouo requested changes

2022-12-13 11:37 UTC, abikouo commented on plugins/module_utils/errors.py
> +__metaclass__ = type
can be removed

2022-12-13 11:37 UTC, abikouo commented on plugins/module_utils/errors.py
> +from __future__ import absolute_import, division, print_function
useless here as we support python3.8+

2022-12-13 11:37 UTC, abikouo commented on plugins/module_utils/models.py
> +__metaclass__ = type
same here

2022-12-13 11:37 UTC, abikouo commented on plugins/module_utils/terraform_commands.py
> +from __future__ import absolute_import, division, print_function
+1

2022-12-13 11:37 UTC, abikouo commented on plugins/module_utils/terraform_commands.py
> +__metaclass__ = type
another one here

2022-12-13 11:37 UTC, abikouo commented on plugins/module_utils/utils.py
> +            raise TerraformError('Could not find state_file "{0}", check the path and try again.'.format(state_file))
```suggestion
        if not os.path.exists(state_file):
            raise TerraformError('Could not find state_file "{0}", check the path and try again.'.format(state_file))
        return ["-state", state_file] 
```
just for code complexity, nothing mandatory

2022-12-13 11:37 UTC, abikouo commented on plugins/modules/terraform_output.py
>          terraform_binary = bin_path
could you please add the same check as the one in the terraform module line 329 to validate that the binary is existing ?

2022-12-14 05:32 UTC, sstanovnik commented
recheck

2022-12-14 05:50 UTC, sstanovnik commented
Thank you for the review @abikouo, I've addressed all your comments.

2022-12-15 16:16 UTC, gravesm approved these changes

2022-12-15 17:20 UTC, abikouo approved these changes

2022-12-15 17:22 UTC, merged